language: python
python:
  - "3.8"
  - "3.9"
before_install:
  - curl -o datasets 'https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets'
  - chmod +x datasets
  - export PATH=$PATH:$PWD
install:
  - pip install .
script:
  - cd $PWD/mashpit/test
  - python test.py
